<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Libs\ClArch.SimpleSpecification\ClArch.SimpleSpecification.csproj" />
        <ProjectReference Include="..\..\Core\ID.Application\ID.Application.csproj" />
        <ProjectReference Include="..\..\Core\ID.Domain\ID.Domain.csproj" />
        <ProjectReference Include="..\..\Extras\JwtKeyBuilder\ID.Jwt.Builder.KeyBuilder\ID.Jwt.KeyBuilder.csproj" />
        <ProjectReference Include="..\ID.Jobs.Quartz\ID.Jobs.Quartz.csproj" />
    </ItemGroup>



	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>ID.Infrastructure.Tests</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>ID.Persistence.Ef.Tests</_Parameter1>
        </AssemblyAttribute>        
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>ID.Tests.Data</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>



    <ItemGroup>
      <PackageReference Include="Hangfire" />
      <PackageReference Include="Hangfire.PostgreSql" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
      <PackageReference Include="Quartz" />
      <PackageReference Include="Quartz.Extensions.Hosting" />
      <PackageReference Include="Quartz.Serialization.Json" />
    </ItemGroup>
    
</Project>
