using ID.Jobs.Quartz.Persistence.Abs;
using Microsoft.Extensions.Logging;

namespace ID.Jobs.Quartz.Persistence.Ef;

internal class PgEfCoreMigrator(
    IDbCommandExecutor _executor,
    IEmbeddedScriptLoader _loader,
    ILogger<PgEfCoreMigrator> _logger)
    : IEfCoreMigrator
{

    private const string _journalTable = QuartzConstants.Db.MigrationsJournalTable.Sql.NAME;
    private const string _journalColPrimary = QuartzConstants.Db.MigrationsJournalTable.Postgres.Columns.PRIMARY;
    private const string _journalColScriptName = QuartzConstants.Db.MigrationsJournalTable.Postgres.Columns.ScriptName;
    private const string _journalColAppliedAt = QuartzConstants.Db.MigrationsJournalTable.Postgres.Columns.AppliedAt;
    private const string _schema = QuartzConstants.Db.Schema;

    public async Task<QuartzMigrateResult> MigrateAsync(Dictionary<string, string> variables, CancellationToken cancellationToken = default)
    {
        var applied = new List<string>();
        var skipped = new List<string>();

        try
        {
            var assembly = IdJobsQrzAssemblyReference.Assembly;
            const string nsPrefix = "ID.Jobs.Quartz.Persistence.DbUp.Postgres.Migrations.";
            var scripts = _loader.LoadEmbeddedSqlScripts(assembly, nsPrefix, variables);

            await _executor.EnsureOpenAsync(cancellationToken);

            await EnsureSchemaExistsAsync(cancellationToken);
            await EnsureJournalTableExistsAsync(cancellationToken);

            foreach (var s in scripts)
            {
                cancellationToken.ThrowIfCancellationRequested();

                // check journal
                var alreadyApplied = await CheckIfMigrationAlreadyApplied(s.Name, cancellationToken);
                if (alreadyApplied)
                {
                    skipped.Add(s.Name);
                    _logger.LogDebug("Skipping already applied script {Script}", s.Name);
                    continue;
                }

                try
                {
                    // Execute full script (Postgres scripts may contain DO blocks)
                    await _executor.ExecuteNonQueryAsync(s.Contents, null, cancellationToken);

                    // Record in journal
                    await RecordMigrationJournal(s.Name, cancellationToken);

                    applied.Add(s.Name);
                    _logger.LogInformation("Applied Quartz migration script {Script}", s.Name);
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Failed to apply Quartz script {Script}", s.Name);
                    return QuartzMigrateResult.Failure($"Failed applying script {s.Name}", ex);
                }
            }

            return QuartzMigrateResult.Success(applied, skipped);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Postgres EF migrator failed");
            return QuartzMigrateResult.Failure("Postgres EF migrator failed", ex);
        }
    }

    //----------------------//

    private async Task EnsureSchemaExistsAsync(CancellationToken cancellationToken)
    {
        await _executor.ExecuteNonQueryAsync($@"CREATE SCHEMA IF NOT EXISTS ""{_schema}"";", null, cancellationToken);
    }

    //----------------------//

    private async Task EnsureJournalTableExistsAsync(CancellationToken cancellationToken)
    {
        var cmd = $@"
CREATE TABLE IF NOT EXISTS ""{_schema}"".""{_journalTable}"" (
    {_journalColPrimary} INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    {_journalColScriptName} VARCHAR(512),
    {_journalColAppliedAt} TIMESTAMPTZ NOT NULL
);";
        await _executor.ExecuteNonQueryAsync(cmd, null, cancellationToken);
    }

    //----------------------//

    private async Task<bool> CheckIfMigrationAlreadyApplied(string name, CancellationToken cancellationToken)
    {
        var checkCommandText = $@"SELECT 1 FROM ""{_schema}"".""{_journalTable}"" WHERE {_journalColScriptName} = @name LIMIT 1;";
        var result = await _executor.ExecuteScalarAsync(checkCommandText, new Dictionary<string, object?> { ["name"] = name }, cancellationToken);
        return result != null;
    }

    //----------------------//

    private async Task RecordMigrationJournal(string name, CancellationToken cancellationToken)
    {
        var insCommandText = $@"INSERT INTO ""{_schema}"".""{_journalTable}"" ({_journalColScriptName}, {_journalColAppliedAt}) VALUES (@name, now());";
        await _executor.ExecuteNonQueryAsync(insCommandText, new Dictionary<string, object?> { ["name"] = name }, cancellationToken);
    }

}//Cls