using ID.Jobs.Quartz.Persistence.Abs;
using Microsoft.Extensions.Logging;

namespace ID.Jobs.Quartz.Persistence.Ef;

internal class PgEfCoreMigrator(
    IDbCommandExecutor _executor,
    IEmbeddedScriptLoader _loader,
    ILogger<PgEfCoreMigrator> _logger)
    : IEfCoreMigrator
{
    private readonly IEmbeddedScriptLoader _loaderLocal = _loader;
    private readonly ILogger _loggerLocal = _logger;

    private const string _journalTable = QuartzConstants.Db.MigrationsJournalTable.Sql.NAME;
    private const string _journalColPrimary = QuartzConstants.Db.MigrationsJournalTable.Postgres.Columns.PRIMARY;
    private const string _journalColScriptName = QuartzConstants.Db.MigrationsJournalTable.Postgres.Columns.ScriptName;
    private const string _journalColAppliedAt = QuartzConstants.Db.MigrationsJournalTable.Postgres.Columns.AppliedAt;
    private const string _schema = QuartzConstants.Db.Schema;

    public async Task<QuartzMigrateResult> MigrateAsync(Dictionary<string, string> variables, CancellationToken cancellationToken = default)
    {
        var applied = new List<string>();
        var skipped = new List<string>();

        try
        {
            var assembly = IdJobsQrzAssemblyReference.Assembly;
            const string nsPrefix = "ID.Jobs.Quartz.Persistence.DbUp.Postgres.Migrations.";
            var scripts = _loaderLocal.LoadEmbeddedSqlScripts(assembly, nsPrefix, variables);

            await _executor.OpenAsync(cancellationToken);

            // Ensure schema exists
            await _executor.ExecuteNonQueryAsync($@"CREATE SCHEMA IF NOT EXISTS ""{_schema}"";", null, cancellationToken);

            // Ensure journal table exists
            await _executor.ExecuteNonQueryAsync($@"
CREATE TABLE IF NOT EXISTS ""{_schema}"".""{_journalTable}"" (
    {_journalColPrimary} INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    {_journalColScriptName} VARCHAR(512),
    {_journalColAppliedAt} TIMESTAMPTZ NOT NULL
);", null, cancellationToken);

            foreach (var s in scripts)
            {
                cancellationToken.ThrowIfCancellationRequested();

                var exists = await _executor.ExecuteScalarAsync($@"SELECT 1 FROM ""{_schema}"".""{_journalTable}"" WHERE {_journalColScriptName} = @name LIMIT 1;", new Dictionary<string, object?> { ["name"] = s.Name }, cancellationToken);
                if (exists != null)
                {
                    skipped.Add(s.Name);
                    _loggerLocal.LogDebug("Skipping already applied script {Script}", s.Name);
                    continue;
                }

                try
                {
                    await _executor.ExecuteNonQueryAsync(s.Contents, null, cancellationToken);

                    await _executor.ExecuteNonQueryAsync($@"INSERT INTO ""{_schema}"".""{_journalTable}"" ({_journalColScriptName}, {_journalColAppliedAt}) VALUES (@name, now());", new Dictionary<string, object?> { ["name"] = s.Name }, cancellationToken);

                    applied.Add(s.Name);
                    _loggerLocal.LogInformation("Applied Quartz migration script {Script}", s.Name);
                }
                catch (Exception ex)
                {
                    _loggerLocal.LogError(ex, "Failed to apply Quartz script {Script}", s.Name);
                    return QuartzMigrateResult.Failure($"Failed applying script {s.Name}", ex);
                }
            }

            return QuartzMigrateResult.Success(applied, skipped);
        }
        catch (Exception ex)
        {
            _loggerLocal.LogError(ex, "Postgres EF migrator failed");
            return QuartzMigrateResult.Failure("Postgres EF migrator failed", ex);
        }
    }
}