<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="IEmailDetails.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\..\Libs\Logging\LoggingHelpers\LoggingHelpers\LoggingHelpers.csproj" />
		<ProjectReference Include="..\..\..\..\Libs\MyResults\MyResults.csproj" />
		<ProjectReference Include="..\..\..\Core\ID.Application\ID.Application.csproj" />
		<ProjectReference Include="..\..\..\Core\ID.GlobalSettings\ID.GlobalSettings.csproj" />
		<ProjectReference Include="..\..\..\Core\ID.IntegrationEvents\ID.IntegrationEvents.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="EventListeners\Subscriptions\SubscriptionsPausedConsumer.cs">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<!-- copy template files to output so they can be overridden at runtime -->
		<None Update="Assets\html-templates\**\*.html">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<!-- Embed templates as a fallback so they are available as resources (useful for single-file publish) -->
		<EmbeddedResource Include="Assets\html-templates\**\*.html" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>ID.Email.SMTP</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>ID.Email.SG</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>ID.Email.Base.Tests</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Scrutor" />
	</ItemGroup>


</Project>
