-- this script is for SQL Server and Azure SQL

-- This initializes the database to pristine for Quartz, by first removing any existing Quartz tables
-- and then recreating them from scratch.
-- Should you only require it to create the tables, set @DropDb to 0.


--IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = '$schema$')
--BEGIN
--     EXEC(N'CREATE SCHEMA ' + QUOTENAME(N'$schema$') + N' AUTHORIZATION [dbo]');
--END

-- Declare a standard T-SQL variable to hold the schema name.
DECLARE @schema_name sysname = N'$schema$'; 
DECLARE @SQL NVARCHAR(MAX);

-- Declare another variable to hold the dynamic SQL command.
DECLARE @create_schema_sql NVARCHAR(MAX); 

-- 1. Check if the schema already exists
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = @schema_name)
BEGIN
    -- 2. Construct the dynamic SQL string, using QUOTENAME for safety
    -- QUOTENAME is essential to protect against SQL Injection and handle special characters
    SET @SQL = 'CREATE SCHEMA ' + QUOTENAME(@schema_name) + ' AUTHORIZATION [dbo];';

    -- 3. Execute the dynamic SQL string
    -- Note: EXEC is required because CREATE SCHEMA must be the first statement in a batch.
    EXEC(@SQL);
END


DECLARE @DropDb BIT = 0; -- Set this to 0 to skip DROP statements, 1 to include them

IF @DropDb = 1
BEGIN
    -- drop indexes if they exist and rebuild if current ones
    DROP INDEX IF EXISTS [IDX_QRTZ_T_J] ON [$schema$].[QRTZ_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_T_JG] ON [$schema$].[QRTZ_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_T_C] ON [$schema$].[QRTZ_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_T_G] ON [$schema$].[QRTZ_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_T_G_J] ON [$schema$].[QRTZ_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_T_STATE] ON [$schema$].[QRTZ_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_T_N_STATE] ON [$schema$].[QRTZ_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_T_N_G_STATE] ON [$schema$].[QRTZ_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_T_NEXT_FIRE_TIME] ON [$schema$].[QRTZ_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_T_NFT_ST] ON [$schema$].[QRTZ_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_T_NFT_MISFIRE] ON [$schema$].[QRTZ_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_T_NFT_ST_MISFIRE] ON [$schema$].[QRTZ_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_T_NFT_ST_MISFIRE_GRP] ON [$schema$].[QRTZ_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_FT_TRIG_INST_NAME] ON [$schema$].[QRTZ_FIRED_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_FT_INST_JOB_REQ_RCVRY] ON [$schema$].[QRTZ_FIRED_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_FT_J_G] ON [$schema$].[QRTZ_FIRED_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_FT_JG] ON [$schema$].[QRTZ_FIRED_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_FT_T_G] ON [$schema$].[QRTZ_FIRED_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_FT_TG] ON [$schema$].[QRTZ_FIRED_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_FT_G_J] ON [$schema$].[QRTZ_FIRED_TRIGGERS];
    DROP INDEX IF EXISTS [IDX_QRTZ_FT_G_T] ON [$schema$].[QRTZ_FIRED_TRIGGERS];

    IF OBJECT_ID(N'[$schema$].[FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS]', N'F') IS NOT NULL
    ALTER TABLE [$schema$].[QRTZ_TRIGGERS] DROP CONSTRAINT [FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS];
    
    IF OBJECT_ID(N'[$schema$].[FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS]', N'F') IS NOT NULL
    ALTER TABLE [$schema$].[QRTZ_CRON_TRIGGERS] DROP CONSTRAINT [FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS];
    
    IF OBJECT_ID(N'[$schema$].[FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS]', N'F') IS NOT NULL
    ALTER TABLE [$schema$].[QRTZ_SIMPLE_TRIGGERS] DROP CONSTRAINT [FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS];
    
    IF OBJECT_ID(N'[$schema$].[FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS]', N'F') IS NOT NULL
    ALTER TABLE [$schema$].[QRTZ_SIMPROP_TRIGGERS] DROP CONSTRAINT [FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS];
    
    IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[$schema$].[FK_QRTZ_JOB_LISTENERS_QRTZ_JOB_DETAILS]') AND parent_object_id = OBJECT_ID(N'[$schema$].[QRTZ_JOB_LISTENERS]'))
    ALTER TABLE [$schema$].[QRTZ_JOB_LISTENERS] DROP CONSTRAINT [FK_QRTZ_JOB_LISTENERS_QRTZ_JOB_DETAILS];
    
    IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[$schema$].[FK_QRTZ_TRIGGER_LISTENERS_QRTZ_TRIGGERS]') AND parent_object_id = OBJECT_ID(N'[$schema$].[QRTZ_TRIGGER_LISTENERS]'))
    ALTER TABLE [$schema$].[QRTZ_TRIGGER_LISTENERS] DROP CONSTRAINT [FK_QRTZ_TRIGGER_LISTENERS_QRTZ_TRIGGERS];
    
    IF OBJECT_ID(N'[$schema$].[QRTZ_CALENDARS]', N'U') IS NOT NULL
    DROP TABLE [$schema$].[QRTZ_CALENDARS];
    
    IF OBJECT_ID(N'[$schema$].[QRTZ_CRON_TRIGGERS]', N'U') IS NOT NULL
    DROP TABLE [$schema$].[QRTZ_CRON_TRIGGERS];
    
    IF OBJECT_ID(N'[$schema$].[QRTZ_BLOB_TRIGGERS]', N'U') IS NOT NULL
    DROP TABLE [$schema$].[QRTZ_BLOB_TRIGGERS];
    
    IF OBJECT_ID(N'[$schema$].[QRTZ_FIRED_TRIGGERS]', N'U') IS NOT NULL
    DROP TABLE [$schema$].[QRTZ_FIRED_TRIGGERS];
    
    IF OBJECT_ID(N'[$schema$].[QRTZ_PAUSED_TRIGGER_GRPS]', N'U') IS NOT NULL
    DROP TABLE [$schema$].[QRTZ_PAUSED_TRIGGER_GRPS];
    
    IF  OBJECT_ID(N'[$schema$].[QRTZ_JOB_LISTENERS]', N'U') IS NOT NULL
    DROP TABLE [$schema$].[QRTZ_JOB_LISTENERS];
    
    IF OBJECT_ID(N'[$schema$].[QRTZ_SCHEDULER_STATE]', N'U') IS NOT NULL
    DROP TABLE [$schema$].[QRTZ_SCHEDULER_STATE];
    
    IF OBJECT_ID(N'[$schema$].[QRTZ_LOCKS]', N'U') IS NOT NULL
    DROP TABLE [$schema$].[QRTZ_LOCKS];

    IF OBJECT_ID(N'[$schema$].[QRTZ_TRIGGER_LISTENERS]', N'U') IS NOT NULL
    DROP TABLE [$schema$].[QRTZ_TRIGGER_LISTENERS];
    
    IF OBJECT_ID(N'[$schema$].[QRTZ_JOB_DETAILS]', N'U') IS NOT NULL
    DROP TABLE [$schema$].[QRTZ_JOB_DETAILS];
    
    IF OBJECT_ID(N'[$schema$].[QRTZ_SIMPLE_TRIGGERS]', N'U') IS NOT NULL
    DROP TABLE [$schema$].[QRTZ_SIMPLE_TRIGGERS];
    
    IF OBJECT_ID(N'[$schema$].[QRTZ_SIMPROP_TRIGGERS]', N'U') IS NOT NULL
    DROP TABLE [$schema$].[QRTZ_SIMPROP_TRIGGERS];
    
    IF OBJECT_ID(N'[$schema$].[QRTZ_TRIGGERS]', N'U') IS NOT NULL
    DROP TABLE [$schema$].[QRTZ_TRIGGERS];
END 



CREATE TABLE [$schema$].[QRTZ_CALENDARS] (
  [SCHED_NAME] nvarchar(120) NOT NULL,
  [CALENDAR_NAME] nvarchar(200) NOT NULL,
  [CALENDAR] varbinary(max) NOT NULL
);

CREATE TABLE [$schema$].[QRTZ_CRON_TRIGGERS] (
  [SCHED_NAME] nvarchar(120) NOT NULL,
  [TRIGGER_NAME] nvarchar(150) NOT NULL,
  [TRIGGER_GROUP] nvarchar(150) NOT NULL,
  [CRON_EXPRESSION] nvarchar(120) NOT NULL,
  [TIME_ZONE_ID] nvarchar(80) 
);

CREATE TABLE [$schema$].[QRTZ_FIRED_TRIGGERS] (
  [SCHED_NAME] nvarchar(120) NOT NULL,
  [ENTRY_ID] nvarchar(140) NOT NULL,
  [TRIGGER_NAME] nvarchar(150) NOT NULL,
  [TRIGGER_GROUP] nvarchar(150) NOT NULL,
  [INSTANCE_NAME] nvarchar(200) NOT NULL,
  [FIRED_TIME] bigint NOT NULL,
  [SCHED_TIME] bigint NOT NULL,
  [PRIORITY] int NOT NULL,
  [STATE] nvarchar(16) NOT NULL,
  [JOB_NAME] nvarchar(150) NULL,
  [JOB_GROUP] nvarchar(150) NULL,
  [IS_NONCONCURRENT] bit NULL,
  [REQUESTS_RECOVERY] bit NULL 
);

CREATE TABLE [$schema$].[QRTZ_PAUSED_TRIGGER_GRPS] (
  [SCHED_NAME] nvarchar(120) NOT NULL,
  [TRIGGER_GROUP] nvarchar(150) NOT NULL 
);

CREATE TABLE [$schema$].[QRTZ_SCHEDULER_STATE] (
  [SCHED_NAME] nvarchar(120) NOT NULL,
  [INSTANCE_NAME] nvarchar(200) NOT NULL,
  [LAST_CHECKIN_TIME] bigint NOT NULL,
  [CHECKIN_INTERVAL] bigint NOT NULL
);

CREATE TABLE [$schema$].[QRTZ_LOCKS] (
  [SCHED_NAME] nvarchar(120) NOT NULL,
  [LOCK_NAME] nvarchar(40) NOT NULL 
);

CREATE TABLE [$schema$].[QRTZ_JOB_DETAILS] (
  [SCHED_NAME] nvarchar(120) NOT NULL,
  [JOB_NAME] nvarchar(150) NOT NULL,
  [JOB_GROUP] nvarchar(150) NOT NULL,
  [DESCRIPTION] nvarchar(250) NULL,
  [JOB_CLASS_NAME] nvarchar(250) NOT NULL,
  [IS_DURABLE] bit NOT NULL,
  [IS_NONCONCURRENT] bit NOT NULL,
  [IS_UPDATE_DATA] bit NOT NULL,
  [REQUESTS_RECOVERY] bit NOT NULL,
  [JOB_DATA] varbinary(max) NULL
);

CREATE TABLE [$schema$].[QRTZ_SIMPLE_TRIGGERS] (
  [SCHED_NAME] nvarchar(120) NOT NULL,
  [TRIGGER_NAME] nvarchar(150) NOT NULL,
  [TRIGGER_GROUP] nvarchar(150) NOT NULL,
  [REPEAT_COUNT] int NOT NULL,
  [REPEAT_INTERVAL] bigint NOT NULL,
  [TIMES_TRIGGERED] int NOT NULL
);

CREATE TABLE [$schema$].[QRTZ_SIMPROP_TRIGGERS] (
  [SCHED_NAME] nvarchar(120) NOT NULL,
  [TRIGGER_NAME] nvarchar(150) NOT NULL,
  [TRIGGER_GROUP] nvarchar(150) NOT NULL,
  [STR_PROP_1] nvarchar(512) NULL,
  [STR_PROP_2] nvarchar(512) NULL,
  [STR_PROP_3] nvarchar(512) NULL,
  [INT_PROP_1] int NULL,
  [INT_PROP_2] int NULL,
  [LONG_PROP_1] bigint NULL,
  [LONG_PROP_2] bigint NULL,
  [DEC_PROP_1] numeric(13,4) NULL,
  [DEC_PROP_2] numeric(13,4) NULL,
  [BOOL_PROP_1] bit NULL,
  [BOOL_PROP_2] bit NULL,
  [TIME_ZONE_ID] nvarchar(80) NULL 
);

CREATE TABLE [$schema$].[QRTZ_BLOB_TRIGGERS] (
  [SCHED_NAME] nvarchar(120) NOT NULL,
  [TRIGGER_NAME] nvarchar(150) NOT NULL,
  [TRIGGER_GROUP] nvarchar(150) NOT NULL,
  [BLOB_DATA] varbinary(max) NULL
);

CREATE TABLE [$schema$].[QRTZ_TRIGGERS] (
  [SCHED_NAME] nvarchar(120) NOT NULL,
  [TRIGGER_NAME] nvarchar(150) NOT NULL,
  [TRIGGER_GROUP] nvarchar(150) NOT NULL,
  [JOB_NAME] nvarchar(150) NOT NULL,
  [JOB_GROUP] nvarchar(150) NOT NULL,
  [DESCRIPTION] nvarchar(250) NULL,
  [NEXT_FIRE_TIME] bigint NULL,
  [PREV_FIRE_TIME] bigint NULL,
  [PRIORITY] int NULL,
  [TRIGGER_STATE] nvarchar(16) NOT NULL,
  [TRIGGER_TYPE] nvarchar(8) NOT NULL,
  [START_TIME] bigint NOT NULL,
  [END_TIME] bigint NULL,
  [CALENDAR_NAME] nvarchar(200) NULL,
  [MISFIRE_INSTR] int NULL,
  [JOB_DATA] varbinary(max) NULL
);
GO

ALTER TABLE [$schema$].[QRTZ_CALENDARS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_CALENDARS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [CALENDAR_NAME]
  );
GO

ALTER TABLE [$schema$].[QRTZ_CRON_TRIGGERS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_CRON_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  );
GO

ALTER TABLE [$schema$].[QRTZ_FIRED_TRIGGERS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_FIRED_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [ENTRY_ID]
  );
GO

ALTER TABLE [$schema$].[QRTZ_PAUSED_TRIGGER_GRPS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_PAUSED_TRIGGER_GRPS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_GROUP]
  );
GO

ALTER TABLE [$schema$].[QRTZ_SCHEDULER_STATE] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_SCHEDULER_STATE] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [INSTANCE_NAME]
  );
GO

ALTER TABLE [$schema$].[QRTZ_LOCKS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_LOCKS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [LOCK_NAME]
  );
GO

ALTER TABLE [$schema$].[QRTZ_JOB_DETAILS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_JOB_DETAILS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [JOB_NAME],
    [JOB_GROUP]
  );
GO

ALTER TABLE [$schema$].[QRTZ_SIMPLE_TRIGGERS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_SIMPLE_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  );
GO

ALTER TABLE [$schema$].[QRTZ_SIMPROP_TRIGGERS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_SIMPROP_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  );
GO

ALTER TABLE [$schema$].[QRTZ_TRIGGERS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  );
GO

ALTER TABLE [$schema$].[QRTZ_BLOB_TRIGGERS] WITH NOCHECK ADD
  CONSTRAINT [PK_QRTZ_BLOB_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  );
GO

ALTER TABLE [$schema$].[QRTZ_CRON_TRIGGERS] ADD
  CONSTRAINT [FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS] FOREIGN KEY
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) REFERENCES [$schema$].[QRTZ_TRIGGERS] (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) ON DELETE CASCADE;
GO

ALTER TABLE [$schema$].[QRTZ_SIMPLE_TRIGGERS] ADD
  CONSTRAINT [FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS] FOREIGN KEY
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) REFERENCES [$schema$].[QRTZ_TRIGGERS] (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) ON DELETE CASCADE;
GO

ALTER TABLE [$schema$].[QRTZ_SIMPROP_TRIGGERS] ADD
  CONSTRAINT [FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS] FOREIGN KEY
  (
	[SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) REFERENCES [$schema$].[QRTZ_TRIGGERS] (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ) ON DELETE CASCADE;
GO

ALTER TABLE [$schema$].[QRTZ_TRIGGERS] ADD
  CONSTRAINT [FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS] FOREIGN KEY
  (
    [SCHED_NAME],
    [JOB_NAME],
    [JOB_GROUP]
  ) REFERENCES [$schema$].[QRTZ_JOB_DETAILS] (
    [SCHED_NAME],
    [JOB_NAME],
    [JOB_GROUP]
  );
GO

-- Create indexes
CREATE INDEX [IDX_QRTZ_T_G_J]                 ON [$schema$].[QRTZ_TRIGGERS](SCHED_NAME, JOB_GROUP, JOB_NAME);
CREATE INDEX [IDX_QRTZ_T_C]                   ON [$schema$].[QRTZ_TRIGGERS](SCHED_NAME, CALENDAR_NAME);

CREATE INDEX [IDX_QRTZ_T_N_G_STATE]           ON [$schema$].[QRTZ_TRIGGERS](SCHED_NAME, TRIGGER_GROUP, TRIGGER_STATE);
CREATE INDEX [IDX_QRTZ_T_STATE]               ON [$schema$].[QRTZ_TRIGGERS](SCHED_NAME, TRIGGER_STATE);
CREATE INDEX [IDX_QRTZ_T_N_STATE]             ON [$schema$].[QRTZ_TRIGGERS](SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_STATE);
CREATE INDEX [IDX_QRTZ_T_NEXT_FIRE_TIME]      ON [$schema$].[QRTZ_TRIGGERS](SCHED_NAME, NEXT_FIRE_TIME);
CREATE INDEX [IDX_QRTZ_T_NFT_ST]              ON [$schema$].[QRTZ_TRIGGERS](SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME);
CREATE INDEX [IDX_QRTZ_T_NFT_ST_MISFIRE]      ON [$schema$].[QRTZ_TRIGGERS](SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_STATE);
CREATE INDEX [IDX_QRTZ_T_NFT_ST_MISFIRE_GRP]  ON [$schema$].[QRTZ_TRIGGERS](SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_GROUP, TRIGGER_STATE);

CREATE INDEX [IDX_QRTZ_FT_INST_JOB_REQ_RCVRY] ON [$schema$].[QRTZ_FIRED_TRIGGERS](SCHED_NAME, INSTANCE_NAME, REQUESTS_RECOVERY);
CREATE INDEX [IDX_QRTZ_FT_G_J]                ON [$schema$].[QRTZ_FIRED_TRIGGERS](SCHED_NAME, JOB_GROUP, JOB_NAME);
CREATE INDEX [IDX_QRTZ_FT_G_T]                ON [$schema$].[QRTZ_FIRED_TRIGGERS](SCHED_NAME, TRIGGER_GROUP, TRIGGER_NAME);
GO