<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>


	<ItemGroup>
		<ProjectReference Include="..\..\..\Libs\ClArch.SimpleSpecification\ClArch.SimpleSpecification.csproj" />
		<ProjectReference Include="..\..\Core\ID.Application\ID.Application.csproj" />
		<ProjectReference Include="..\..\Core\ID.Domain\ID.Domain.csproj" />
		<ProjectReference Include="..\..\Core\ID.GlobalSettings\ID.GlobalSettings.csproj" />
		<ProjectReference Include="..\..\Extras\JwtKeyBuilder\ID.Jwt.Builder.KeyBuilder\ID.Jwt.KeyBuilder.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CrystalQuartz.AspNetCore" />
		<!--	<PackageReference Include="dbup" />
		<PackageReference Include="dbup-postgresql" />
		<PackageReference Include="dbup-sqlserver" />-->
		<PackageReference Include="Polly" />
		<PackageReference Include="Quartz" />
		<PackageReference Include="Quartz.Extensions.Hosting" />
		<PackageReference Include="Quartz.Serialization.Json" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="EFCore.NamingConventions" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
	</ItemGroup>


	<!-- Embedded SQL script for optional DB initialization -->
	<ItemGroup>
		<!-- embed all SQL migrations for SQL Server -->
		<EmbeddedResource Include="Persistence\Ef\SqlServer\Migrations\*.sql.template" />
		<!-- embed Postgres migrations similarly -->
		<EmbeddedResource Include="Persistence\Ef\Postgres\Migrations\*.sql.template" />
	</ItemGroup>


	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>ID.Jobs.Quartz.Tests</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>


	<ItemGroup>
	  <Folder Include="Tests\" />
	</ItemGroup>

</Project>