<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Persistence\Initializers\Postgres\Migrations\001-create-quartz-3_15-1.sql" />
    <None Remove="Persistence\Initializers\SqlServer\Migrations\001-create-quartz-3_15-1.sql" />
    <None Remove="Persistence\Initializers\SqlServer\Migrations\002-add-myid-test-column.sql" />
  </ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\..\..\Libs\ClArch.SimpleSpecification\ClArch.SimpleSpecification.csproj" />
		<ProjectReference Include="..\..\Core\ID.Application\ID.Application.csproj" />
		<ProjectReference Include="..\..\Core\ID.Domain\ID.Domain.csproj" />
		<ProjectReference Include="..\..\Extras\JwtKeyBuilder\ID.Jwt.Builder.KeyBuilder\ID.Jwt.KeyBuilder.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="dbup" />
		<PackageReference Include="dbup-postgresql" />
		<PackageReference Include="dbup-sqlserver" />
		<PackageReference Include="Quartz" />
		<PackageReference Include="Quartz.Extensions.Hosting" />
		<PackageReference Include="Quartz.Serialization.Json" />
	</ItemGroup>


  <!-- Embedded SQL script for optional DB initialization -->
  <ItemGroup>
	  <!-- embed all SQL migrations for SQL Server -->
	  <EmbeddedResource Include="Persistence\Initializers\SqlServer\Migrations\*.sql" />
	  <!-- embed Postgres migrations similarly -->
	  <EmbeddedResource Include="Persistence\Initializers\Postgres\Migrations\*.sql" />
  </ItemGroup>

</Project>
