<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


	<ItemGroup>
		<ProjectReference Include="..\..\..\Libs\ClArch.SimpleSpecification\ClArch.SimpleSpecification.csproj" />
		<ProjectReference Include="..\..\Core\ID.Application\ID.Application.csproj" />
		<ProjectReference Include="..\..\Core\ID.Domain\ID.Domain.csproj" />
		<ProjectReference Include="..\..\Extras\JwtKeyBuilder\ID.Jwt.Builder.KeyBuilder\ID.Jwt.KeyBuilder.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Quartz" />
		<PackageReference Include="Quartz.Extensions.Hosting" />
		<PackageReference Include="Quartz.Serialization.Json" />
	</ItemGroup>


  <!-- Embedded SQL script for optional DB initialization -->
  <ItemGroup>
    <EmbeddedResource Include="Persistence\Initializers\SQL\QUARTZ_INIT_SQL.sql" />
  </ItemGroup>

</Project>
