<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<!--<PackageReference Include="Microsoft.Extensions.Identity.Core" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.Data.SqlClient" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />-->
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>ID.Persistence.Ef.SQL</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>ID.Persistence.Ef.Postgres</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>ID.Persistence.Ef.Tests</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>ID.Tests.Data</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Core\ID.Application\ID.Application.csproj" />
	  <ProjectReference Include="..\..\Core\ID.Domain.Repos\ID.Domain.Repos.csproj" />
	</ItemGroup>

</Project>
